'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict');
const text=name=>fs.readFileSync(path.join(__dirname,name),'utf8');
function extract(start,end){const s=text('index.html'),a=s.indexOf(start),b=s.indexOf(end,a);assert(a>=0&&b>a,start);return s.slice(a,b);}
function helpers(){const c={window:{}};vm.runInNewContext(text('payment-source-ui.js'),c);vm.runInNewContext(text('payment-method-brand.js'),c);return c.window;}
test('all proposed scripts parse',()=>{for(const file of ['payment-source-ui.js','payment-method-brand.js'])new vm.Script(text(file));for(const m of text('index.html').matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))new vm.Script(m[1]);});
test('five sending apps map to GCash and BDO aliases retain the proper icon',()=>{const w=helpers();for(const code of ['gcash','bdo_pay','bpi','gotyme','maribank']){assert.equal(w.PaymentSourceUI.destination(code),'gcash');assert(w.PaymentMethodBrand.iconSrc(code).endsWith('.png'));}for(const alias of ['bdo','bdo_pay','bdopay']){assert.equal(w.PaymentSourceUI.uiCode(alias),'bdopay');assert.equal(w.PaymentMethodBrand.iconSrc(alias),'assets/payment-methods/bdo-pay.png');}assert.equal(w.PaymentSourceUI.label('bdo_pay'),'BDO Pay → GCash');assert.equal(w.PaymentSourceUI.label('maribank'),'MariBank → GCash');assert.equal(w.PaymentSourceUI.destination('pnb'),'pnb');assert.equal(w.PaymentSourceUI.destination('cash'),'cash');});
test('source-specific references preserve complete GoTyme and MariBank identifiers',()=>{const h=helpers().PaymentSourceUI;assert.equal(h.normalizeReference('GT-TEST12345','gotyme'),'GT-TEST12345');assert.equal(h.normalizeReference('MB-20260908-ABC123','maribank'),'MB-20260908-ABC123');assert.equal(h.referenceError('GT-TEST12345','gotyme'),'');assert.equal(h.referenceError('MB-20260908-ABC123','maribank'),'');assert.equal(h.referenceError('BN-20260908-12345678','bdo_pay'),'');assert(h.referenceError('INVOICE-12345','bdo_pay'));assert.equal(h.referenceError('ABCD EFGH 1234','maya'),'');assert.equal(h.normalizeReference('MAYA-20260909-123456789','maya'),'MAYA-20260909-123456789');assert.equal(h.referenceError('MAYA-20260909-123456789','maya'),'');assert(h.referenceError('123','maya'));assert.equal(h.destination('maya'),'maya');assert.equal(h.label('maya'),'Maya');assert.equal(h.referenceError('1234567890123','bpi'),'');assert(h.referenceError('BPI-TRANSFER-123','bpi'));assert.equal(h.referenceError('1234567890123','gcash'),'');assert(h.referenceError('123456','gcash'));assert.equal(h.referenceRules('gotyme').inputMode,'text');assert.equal(h.referenceRules('maribank').maxLength,64);});
test('balance selector preserves active digital codes and excludes public cash',()=>{const w=helpers();w.PB_PLATFORM_V1=true;const c={window:w};vm.runInNewContext(extract('function balancePaymentMethods(balance) {','function balanceMethodDetailHtml('),c);const codes=['gcash','bdo_pay','maya','bpi','gotyme','maribank','pnb','cash'];assert.deepEqual(Array.from(c.balancePaymentMethods({paymentMethods:codes.map(code=>({code}))}),x=>x.code),codes.slice(0,-1));w.PB_PLATFORM_V1=false;assert.equal(c.balancePaymentMethods({paymentMethods:codes.map(code=>({code}))}).length,8);});
test('public settings preserve server enablement and identity; cash stays staff-only',()=>{const w=helpers();w.PB_PLATFORM_V1=true;const methods=['gcash','bdopay','maya','bpi','gotyme','maribank','pnb','cash'];w.PB_PAYMENT_METHOD_CODES={};w.PB_PAYMENT_METHODS_BY_CODE={};for(const method of methods){const code=method==='bdopay'?'bdo_pay':method;w.PB_PAYMENT_METHOD_CODES[method]=code;w.PB_PAYMENT_METHODS_BY_CODE[code]={code,uiCode:method,displayName:w.PaymentSourceUI.name(method),accountName:'Test-only receiver',accountReference:'test-only-account',qrImageUrl:'https://test.invalid/qr.png',instructions:'Test instructions'};}
 const el={value:'gcash',style:{},classList:{remove(){}}};const c={window:w,ALL_PAYMENT_METHODS:methods,PAYMENT_METHOD_FALLBACK_NAMES:Object.fromEntries(methods.map(m=>[m,w.PaymentSourceUI.name(m)])),safePaymentQrUrl:x=>x,paymentMethods:Object.fromEntries(methods.map(m=>[m,false])),gcashSettings:{},paymentReceiverSettings:{},paymentAcceptanceMode:'',document:{querySelectorAll:()=>[]},$:id=>id==='bPay'?el:null,assignPaymentQr(){},pickPay(){},updatePaymentAmountUI(){}};
 vm.runInNewContext(extract('function paymentReceiverFromSettings(','function preparePaymentStep()'),c);
 const settings=Object.fromEntries(methods.map(m=>['payment_method_'+m,'1']));c.applyPaymentSettings(settings);for(const m of methods.filter(m=>m!=='cash'))assert.equal(c.paymentMethods[m],true,m);assert.equal(c.paymentMethods.cash,false);assert.equal(c.paymentReceiverSettings.bdopay.backendCode,'bdo_pay');assert.equal(c.paymentReceiverSettings.maribank.number,'test-only-account');settings.payment_method_maribank='0';c.applyPaymentSettings(settings);assert.equal(c.paymentMethods.maribank,false);delete w.PB_PAYMENT_METHODS_BY_CODE.gotyme;c.applyPaymentSettings(settings);assert.equal(c.paymentMethods.gotyme,false);
});

function clockContext({server=true,remaining=300,access=true}={}) {
 let now=Date.parse('2026-09-08T00:00:00Z');const callbacks={},events={},announcements=[];let cancellations=0,closed=0,polls=0;
 class ClockDate extends Date {constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}}
 const elements=new Map();function el(id){if(!elements.has(id)){const classes=new Set(id==='bookModal'?['active']:[]);elements.set(id,{id,style:{display:'none'},textContent:'',inert:false,classes,classList:{contains:k=>classes.has(k),add:k=>classes.add(k),remove:k=>classes.delete(k),toggle:(k,v)=>v?classes.add(k):classes.delete(k)},setAttribute(){},removeAttribute(){},querySelectorAll:()=>[],focus(){}});}return elements.get(id);}
 const c={Date:ClockDate,Set,window:{PB_PLATFORM_V1:server,addEventListener:(name,fn)=>events['window:'+name]=fn},document:{hidden:false,addEventListener:(name,fn)=>events['document:'+name]=fn},$:el,_platformBookingAccess:access?{reference:'TEST-REFERENCE',bookingToken:'test-token',expiresAt:new Date(now+remaining*1000).toISOString(),booking:{status:"pending_payment",reservationHeld:true,expiresAt:new Date(now+remaining*1000).toISOString()}}:null,_reservationStartedAt:new Date(now-60000).toISOString(),RESERVATION_MINUTES:15,_countdownInterval:null,_countdownTick:null,_reservationIntroTimeout:null,setInterval:fn=>{callbacks.interval=fn;return 1;},clearInterval:()=>{delete callbacks.interval;},setTimeout:fn=>{callbacks.timeout=fn;return 2;},clearTimeout:()=>{delete callbacks.timeout;},requestAnimationFrame:fn=>fn(),formatPhTime12:date=>date.toISOString(),savePlatformStatusAccess(){},closeBookModal(){closed++;c.stopSlotCountdown();},startSavedPlatformBookingPolling:async()=>{polls++;},toast:message=>announcements.push(message),cancelBookingWizard:()=>{cancellations++;}};
 vm.runInNewContext(extract('function platformHoldIsUsable(', 'function platformPolicyContextStillCurrent('),c);vm.runInNewContext(extract('function bookingReservationDeadlineMs(','function guestResumeFormDraft()'),c);vm.runInNewContext(extract('function updatePaymentWindowText() {','function paymentInstructionText()'),c);vm.runInNewContext(extract('function setBookingIntroContentInert(', '/* ── BOOKING WIZARD ── */'),c);return{c,elements,events,callbacks,advance:ms=>now+=ms,counts:()=>({cancellations,closed,polls}),announcements};
}
test('platform countdown uses the server deadline and ignores a fresh initial 15 minutes',()=>{const {c,elements}=clockContext();assert.equal(c.startSlotCountdown(900),true);assert.equal(elements.get('scdTimerBig').textContent,'05:00');assert.equal(elements.get('bPayWindowEnd').textContent,'2026-09-08T00:05:00.000Z');const before=c._platformBookingAccess.booking.expiresAt;c.startSlotCountdown(900);assert.equal(c._platformBookingAccess.booking.expiresAt,before);assert.equal(elements.get('scdTimerBig').textContent,'05:00');});
test('waking a throttled page catches up immediately without restarting the hold',()=>{const {c,elements,events,advance}=clockContext();c.startSlotCountdown();advance(125000);events['document:visibilitychange']();assert.equal(elements.get('scdTimerBig').textContent,'02:55');advance(10000);events['window:pageshow']();assert.equal(elements.get('scdTimerBig').textContent,'02:45');advance(5000);events['window:focus']();assert.equal(elements.get('scdTimerBig').textContent,'02:40');});
test('expiry clears the timer and checks private status without cancelling a receipt',()=>{const {c,elements,advance,events,counts}=clockContext();c.startSlotCountdown();advance(301000);events['window:focus']();assert.equal(elements.get('scdTimerBig').textContent,'00:00');assert.deepEqual(counts(),{cancellations:0,closed:1,polls:1});assert.equal(c._countdownTick,null);assert.equal(c._platformBookingAccess.reference,'TEST-REFERENCE');});
test('intro cannot show or start fifteen minutes without a real server deadline',()=>{const {c,elements}=clockContext({access:false});assert.equal(c.startSlotCountdown(900),false);assert.equal(c.showBookingIntro(),false);assert.equal(elements.get('slotCountdown').style.display,'none');});
test('intro displays remaining server time; dismissing it leaves the deadline intact',()=>{const {c,elements,callbacks}=clockContext({remaining:899});c.startSlotCountdown();const before=c._platformBookingAccess.booking.expiresAt;assert.equal(c.showBookingIntro(),true);assert.equal(elements.get('bookingIntroTimer').textContent,'14:59');assert.equal(elements.get('bookingIntro').inert,false);callbacks.timeout();assert.equal(elements.get('bookingIntro').inert,true);assert.equal(c._platformBookingAccess.booking.expiresAt,before);assert.equal(typeof c._countdownTick,'function');});
