'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=file=>fs.readFileSync(file,'utf8');
const part=(file,start,end)=>{const text=source(file),a=text.indexOf(start),b=text.indexOf(end,a);assert.ok(a>=0&&b>a);return text.slice(a,b);};
const url='https://neqvrwtofiolcuxewdze.supabase.co/storage/v1/object/public/tenant-public-assets/f19f457a-68e2-42ea-9f8e-1f6e8ac84b3a/payment-qr/gcash/7e558563-115d-46f1-b5ae-3b9ee24c5d83.jpg';
function adapter(error=null){const calls=[],revisions=[];const c={URL,PB_PLATFORM_V1:true,PB_PAGE_DATA_SCOPE:'manager',PB_TENANT_SLUG:'pickle-street-tugbok',SUPABASE_URL:'https://neqvrwtofiolcuxewdze.supabase.co',_pbTenantHostname:()=> 'picklestreet.pages.dev',_pbCaptureBusinessRevision:r=>revisions.push(r),_pbClearFastCache(){},_extractFnError:()=> 'Reload settings',_sb:{rpc:async(name,args)=>{calls.push({name,args});return{data:{tenantRevision:'new'},error};}}};vm.createContext(c);vm.runInContext('DB={'+part('supabase-config.js','  async removeTenantPaymentQr(','  async saveTenantPlatformBilling(')+'}',c);return{c,calls,revisions};}
test('QR removal uses managed compare-and-swap with exact venue, method and previous asset',async()=>{const{c,calls,revisions}=adapter();await c.DB.removeTenantPaymentQr({methodCode:'gcash',url});assert.equal(calls[0].name,'manage_tenant_payment_qr_asset');assert.equal(calls[0].args.p_tenant_slug,'pickle-street-tugbok');assert.equal(calls[0].args.p_expected_qr_image_url,url);assert.match(calls[0].args.p_expected_qr_storage_path,/\/payment-qr\/gcash\//);assert.equal(calls[0].args.p_remove,true);assert.equal(calls[0].args.p_qr_storage_path,null);assert.equal(revisions[0].tenantRevision,'new');});
test('untrusted QR URL and failed removal never update the saved revision',async()=>{const{c,calls,revisions}=adapter({message:'stale'});await assert.rejects(c.DB.removeTenantPaymentQr({methodCode:'gcash',url:'https://example.invalid/qr.png'}),/Reload/);assert.equal(calls.length,0);await assert.rejects(c.DB.removeTenantPaymentQr({methodCode:'gcash',url}),/Reload/);assert.equal(revisions.length,0);});
test('QR remove UI preserves preview on error and clears it only after server confirmation',async()=>{for(const failure of [true,false]){const previews=[],statuses=[];const elements={row:{dataset:{code:'gcash',displayName:'GCash'}},url:{value:url},uploadButton:{disabled:false}};const button={disabled:false};const c={platformQrElements:()=>elements,confirm:()=>true,DB:{removeTenantPaymentQr:async()=>{if(failure)throw Error('Reload settings');}},setPlatformQrPreview:(_e,u)=>previews.push(u),setPlatformQrStatus:(_e,s)=>statuses.push(s)};vm.createContext(c);vm.runInContext(part('admin.html','async function removePlatformPaymentQr(','function platformActivationReadinessChecks('),c);await c.removePlatformPaymentQr(button);assert.deepEqual(previews,failure?[]:['']);assert.match(statuses.at(-1),failure?/Reload/:/removed/);assert.equal(button.disabled,false);assert.equal(elements.uploadButton.disabled,false);}});
test('upload success accurately reports immediate QR publication',()=>{assert.match(source('admin.html'),/QR image saved\. Save Payment Settings if you also changed/);assert.doesNotMatch(source('admin.html'),/Uploaded\. Click Save Payment Settings to publish it/);assert.match(source('payment-settings.js'),/QR images are saved immediately after upload/);});
