import assert from 'node:assert/strict';
import {sendMailerooEmail as sendGeneric,type SendMailerooOptions} from './maileroo.ts';
import {sendMailerooEmail,PICKLESTREET_OWNER_REPLY_EMAIL} from './picklestreet-mail.ts';
const defaults:SendMailerooOptions={apiKey:'test-key',fromAddress:'bookings@example.test',fromName:'Test venue',replyTo:'support@example.test',to:'player@example.test',subject:'Confirmation',html:'<p>Confirmed</p>',plainText:'Confirmed'};
async function capture(replyTo: string|string[], generic=false){let body:Record<string,unknown>={};const fetcher=(async(_url:unknown,init:RequestInit)=>{body=JSON.parse(String(init.body));return Response.json({success:true,data:{reference_id:'test'}});}) as typeof fetch;await (generic?sendGeneric:sendMailerooEmail)({...defaults,replyTo,fetcher});return body;}
Deno.test('Pickle Street replies include court owner and existing support inbox',async()=>{const body=await capture('support@example.test');assert.deepEqual((body.reply_to as {address:string}[]).map(x=>x.address),[PICKLESTREET_OWNER_REPLY_EMAIL,'support@example.test']);assert.deepEqual(body.to,[{address:'player@example.test'}]);assert.equal(body.cc,undefined);assert.equal(body.bcc,undefined);});
Deno.test('reply addresses are normalized and deduplicated',async()=>{const body=await capture(['DAAP.PERSPECTIVES@GMAIL.COM','support@example.test','support@example.test']);assert.equal((body.reply_to as unknown[]).length,2);const single=await capture(PICKLESTREET_OWNER_REPLY_EMAIL);assert.equal((single.reply_to as {address:string}).address,PICKLESTREET_OWNER_REPLY_EMAIL);});
Deno.test('generic transport does not add a different venues owner',async()=>{const body=await capture('other@example.test',true);assert.deepEqual(body.reply_to,{address:'other@example.test',display_name:'Test venue'});});
Deno.test('invalid reply addresses fail before a message is sent',async()=>{let called=false;await assert.rejects(()=>sendMailerooEmail({...defaults,replyTo:'wrong\r\nBcc: person@example.test',fetcher:(async()=>{called=true;return Response.json({success:true});}) as typeof fetch}));assert.equal(called,false);});
