'use strict';
module.exports = Object.freeze([
  'index.html', 'admin.html', 'login.html', 'booking-management.html', '404.html',
  'tenant-config.js', 'supabase-config.js', 'supabase.min.js', 'chart.min.js',
  'booking-balance.js', 'blocked-date-access.js', 'receipt-pending.js',
  'court-pricing.js',
  'admin-group-reschedule.js', 'admin-group-reschedule.css',
  'payment-method-brand.js', 'payment-method-brand.css', 'payment-settings.js', 'payment-settings.css',
  'payment-source-ui.js',
  'assets/payment-methods/gcash.png', 'assets/payment-methods/bdo-pay.png',
  'assets/payment-methods/maya.png', 'assets/payment-methods/bpi.png',
  'assets/payment-methods/gotyme.png', 'assets/payment-methods/maribank.png',
  'assets/payment-methods/pnb.png', 'assets/payment-methods/cash.svg',
  'assets/maya-transaction-details-receipt.png',
  'open-play-data.js', 'open-play-public.js', 'open-play-admin.js', 'open-play-reporting.js',
  'open-play.css', 'open-play-admin.css', 'open-play-reporting.css',
  'pickle-street.css', 'pickle-street.js', 'booking-management.css', 'booking-management.js',
  'assets/pickle-street-mark.svg', 'assets/pickle-street-courts.jpg', 'logopickle.jpg',
  'assets/pickle-street-logo-transparent.png',
  'assets/pickle-street-share-v1.jpg',
  'assets/payment-not-configured.svg', '_headers', '_worker.js',
]);
